### PR TITLE
Unable to configure flyway.datasources.*.ignore-migration-patterns

### LINKED ISSUE #309: Unable to configure flyway.datasources.*.ignore-migration-patterns
### Expected Behavior

[flyway.datasources.*.ignore-migration-patterns.ignore-migration-patterns](https://flywaydb.org/documentation/configuration/parameters/ignoreMigrationPatterns) `"*:missing"` should allow us to ignore missing migrations, which is useful for concurrent development of different features.

### Actual Behaviour

When starting the application which runs migrations

```
java.lang.NullPointerException: null\n\tat org.flywaydb.core.internal.info.MigrationInfoImpl.lambda$validate$0(MigrationInfoImpl.java:317)
```

This happens because [flyway 8.0.3](https://flywaydb.org/documentation/learnmore/releaseNotes#8.0.3) added an `ignoreMigrationPatterns(ValidatePattern... ignoreMigrationPatterns)` overload. `micronaut-inject-java` generates a mapping for both the CSV string and the object array, but the object array call happens to be last, therefore is the one that matters.

Creating this bug here mainly for documentation purposes. But I'd also be interested if there was a fix that I am not seeing because I can't think of an easy one.

### Steps To Reproduce

```yaml
# application.yaml
flyway:
  datasources:
    default:
      ignore-migration-patterns: "*:missing"
```

- creates branches A and B from main
- checkout branch A, create migration A, and start application to migrate
- checkout branch B, create migration B, and start application to migrate
  - note: branch B does not have migration A
  
### Workarounds

Unfortunately, we cannot use the deprecated `ignoreMissingMigrations` as a workaround, because `micronaut-inject-java` does not allow the setting of `@Deprecated` properties.

However, we can downgrade to a version of flyway that doesn't have that overload.

```gradle
constraints {
  implementation("org.flywaydb:flyway-core") {
    version {
      strictly "8.0.2"
    }
  }
}
```

Downgrading to a version of flyway that does not have `ignoreMissingMigrations` deprecated might allow us to set `ignore-missing-migrations: true` but I haven't tried that.

Also if there were a way to explicitly support a deprecated property in `micronaut-inject-java` that might work too.

### Environment Information

- io.micronaut.flyway:micronaut-flyway:5.1.2
- org.flywaydb:flyway-core:8.4.2

### Example Application

_No response_

### Version

3.3.2

### PR DESCRIPTION
**Pull request by timyates**
Supersedes https://github.com/micronaut-projects/micronaut-flyway/pull/325 with a small test addition (also to get Sonar to run)

Fixes #309

### CODE REVIEW

**Review by alvarosanchez — APPROVED** [review]

File: flyway/src/main/java/io/micronaut/flyway/ValidatePatternTypeConverter.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+ * @since 5.4.1
+ */
+@Singleton
+public class ValidatePatternTypeConverter implements TypeConverter<String, ValidatePattern> {
+
+    @Override
+    public Optional<ValidatePattern> convert(String pattern,
+                                             Class<ValidatePattern> targetType,
+                                             ConversionContext context) {
+        if (pattern == null || pattern.trim().length() == 0) {
```
Comment (sdelamo) [inline flyway/src/main/java/io/micronaut/flyway/ValidatePatternTypeConverter.java:39]: use `StringUtils.isEmpty(patterns)`

**Review by sdelamo — CHANGES_REQUESTED** [review]

File: flyway/src/main/java/io/micronaut/flyway/ValidatePatternTypeConverter.java (hunk 1 above)
Comment (sdelamo) [reply flyway/src/main/java/io/micronaut/flyway/ValidatePatternTypeConverter.java:39]: nevermind, `StringUtils::isEmpty` will not do the `trim`

**Review by sdelamo — APPROVED** [review]
